---
- name: Install httpd and wget website
  hosts: webserver
  become: true
  vars:
    website_url: "https://datakloudservice.com/"
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
  - name: Start httpd service
    service:
      name: httpd
      state: started
  - name: Install wget
    yum:
      name: wget
      state: latest
    yum:
      name: unzip
      state: latest
  - name: Download website from the internet using wget
    command: wget -r {{ website_url }} -P /var/www/html
